name: ultra
channels:
  - conda-forge
  - bioconda
  - r
  - bcbio
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py36h5fab9bb_1
  - dataclasses=0.7=pyhe4b4509_6
  - dnaio=0.5.0=py36h4c5857e_0
  - isa-l=2.30.0=ha770c72_2
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgomp=9.3.0=h2828fa1_18
  - libstdcxx-ng=9.3.0=h6de172a_18
  - ncurses=6.2=h58526e2_4
  - openssl=1.1.1j=h7f98852_0
  - pigz=2.5=h27826a3_0
  - pip=21.0.1=pyhd8ed1ab_0
  - python=3.6.13=hffdb5ce_0_cpython
  - python-isal=0.5.0=py36h8f6f2f9_0
  - python_abi=3.6=1_cp36m
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - sqlite=3.34.0=h74cdb3f_0
  - tk=8.6.10=h21135ba_1
  - ultraplex=1.1.3=py36h4c5857e_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xopen=1.1.0=py36h5fab9bb_1
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
